# Generated by Django 5.0.7 on 2024-07-16 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_libros', '0003_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resumen',
            name='libro',
        ),
        migrations.RemoveField(
            model_name='resumen',
            name='usuario',
        ),
        migrations.DeleteModel(
            name='Biblioteca',
        ),
        migrations.DeleteModel(
            name='Resumen',
        ),
    ]
