# Generated by Django 5.0.7 on 2024-07-24 16:42

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_libros', '0005_favorito'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='favorito',
            options={'verbose_name': 'Favorito', 'verbose_name_plural': 'Favoritos'},
        ),
        migrations.AddField(
            model_name='favorito',
            name='fecha_agregado',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
