# Generated by Django 5.0.7 on 2024-07-25 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_libros', '0006_alter_favorito_options_favorito_fecha_agregado'),
    ]

    operations = [
        migrations.AddField(
            model_name='libro',
            name='google_id',
            field=models.CharField(default='', max_length=100, unique=True),
        ),
    ]
