# Generated by Django 5.0.7 on 2024-07-25 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_libros', '0007_libro_google_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libro',
            name='autor',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='libro',
            name='fecha_publicacion',
            field=models.CharField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='libro',
            name='titulo',
            field=models.CharField(max_length=200),
        ),
    ]
