# Generated by Django 5.0.7 on 2024-07-25 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_libros', '0009_alter_libro_autor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libro',
            name='imagen_portada',
            field=models.TextField(),
        ),
    ]
