# Generated by Django 5.0.7 on 2024-07-25 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_libros', '0010_alter_libro_imagen_portada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libro',
            name='autor',
            field=models.JSONField(default=list),
        ),
    ]
